In [45]:
!pip install pandas
import pandas as pd

raw = [
    {"date":"2026-01-01", "time":"09:10", "store":"A", "menu":"Americano", "price":"4,500원", "qty":"2", "paid":"TRUE"},
    {"date":"2026/01/01", "time":"09:12", "store":"A", "menu":"Latte",     "price":"5000",   "qty":1,   "paid":"True"}, # /
    {"date":"2026-01-02", "time":"12:30", "store":"A", "menu":"Latte",     "price":None,     "qty":2,   "paid":"FALSE"},
    {"date":"2026-01-03", "time":"18:05", "store":"B", "menu":"Mocha",     "price":"5500",   "qty":None,"paid":True},
    {"date":"2026-01-03", "time":"18:05", "store":"B", "menu":"Mocha",     "price":"5500",   "qty":None,"paid":True},  # 중복
    {"date":"2026-01-04", "time":"08:55", "store":"B", "menu":"Americano ", "price":"4500",  "qty":"1", "paid":"TRUE"}, # 공백
    {"date":"2026-01-04", "time":"08:58", "store":"A", "menu":"latte",     "price":"5,000",  "qty":"3", "paid":"TRUE"}, # 소문자
]
df = pd.DataFrame(raw)

df

22148.48s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Requirement already satisfied: pandas in ./.venv/lib/python3.9/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in ./.venv/lib/python3.9/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.9/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.9/site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

         date   time store        menu   price   qty   paid
0  2026-01-01  09:10     A   Americano  4,500원     2   TRUE
1  2026/01/01  09:12     A       Latte    5000     1   True
2  2026-01-02  12:30     A       Latte    None     2  FALSE
3  2026-01-03  18:05     B       Mocha    5500  None   True
4  2026-01-03  18:05     B       Mocha    5500  None   True
5  2026-01-04  08:55     B  Americano     4500     1   TRUE
6  2026-01-04  08:58     A       latte   5,000     3   TRUE

In [3]:
df.shape

(7, 7)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    7 non-null      object
 1   time    7 non-null      object
 2   store   7 non-null      object
 3   menu    7 non-null      object
 4   price   6 non-null      object
 5   qty     5 non-null      object
 6   paid    7 non-null      object
dtypes: object(7)
memory usage: 520.0+ bytes

In [5]:
df.describe(include="all")

              date   time store   menu price qty  paid
count            7      7     7      7     6   5     7
unique           5      6     2      5     5   5     4
top     2026-01-03  18:05     A  Latte  5500   2  TRUE
freq             2      2     4      2     2   1     3

In [6]:
df.loc[0]

date     2026-01-01
time          09:10
store             A
menu      Americano
price        4,500원
qty               2
paid           TRUE
Name: 0, dtype: object

In [7]:
df.iloc[0]

date     2026-01-01
time          09:10
store             A
menu      Americano
price        4,500원
qty               2
paid           TRUE
Name: 0, dtype: object

In [8]:
df.loc[0:2]   # 끝 포함

         date   time store       menu   price qty   paid
0  2026-01-01  09:10     A  Americano  4,500원   2   TRUE
1  2026/01/01  09:12     A      Latte    5000   1   True
2  2026-01-02  12:30     A      Latte    None   2  FALSE

In [9]:
df.iloc[0:2]  # 끝 미포함

         date   time store       menu   price qty  paid
0  2026-01-01  09:10     A  Americano  4,500원   2  TRUE
1  2026/01/01  09:12     A      Latte    5000   1  True

In [46]:
cols = ["date","time","store","menu","price","qty","paid"]
df2 = df[cols].copy()
df2.head()

         date   time store       menu   price   qty   paid
0  2026-01-01  09:10     A  Americano  4,500원     2   TRUE
1  2026/01/01  09:12     A      Latte    5000     1   True
2  2026-01-02  12:30     A      Latte    None     2  FALSE
3  2026-01-03  18:05     B      Mocha    5500  None   True
4  2026-01-03  18:05     B      Mocha    5500  None   True

In [47]:
df2["paid"] = df2["paid"].astype(str).str.strip().str.lower()
df2["paid"].value_counts()

paid
true     6
false    1
Name: count, dtype: int64

In [48]:
cond_paid = df2["paid"].isin(["true"])
paid_df = df2.loc[cond_paid]
paid_df

         date   time store        menu   price   qty  paid
0  2026-01-01  09:10     A   Americano  4,500원     2  true
1  2026/01/01  09:12     A       Latte    5000     1  true
3  2026-01-03  18:05     B       Mocha    5500  None  true
4  2026-01-03  18:05     B       Mocha    5500  None  true
5  2026-01-04  08:55     B  Americano     4500     1  true
6  2026-01-04  08:58     A       latte   5,000     3  true

In [49]:
cond_storeA = (df2["store"] == "A")
cond_morning = df2["time"].str.startswith("09")

df_morning_A = df2.loc[cond_paid & cond_storeA & cond_morning, ["date","time","store","menu","price","qty","paid"]]
df_morning_A

         date   time store       menu   price qty  paid
0  2026-01-01  09:10     A  Americano  4,500원   2  true
1  2026/01/01  09:12     A      Latte    5000   1  true

In [50]:
df2.sort_values(by=["date","time"],ascending=[True, True]).head()

         date   time store        menu   price   qty   paid
0  2026-01-01  09:10     A   Americano  4,500원     2   true
2  2026-01-02  12:30     A       Latte    None     2  false
3  2026-01-03  18:05     B       Mocha    5500  None   true
4  2026-01-03  18:05     B       Mocha    5500  None   true
5  2026-01-04  08:55     B  Americano     4500     1   true

In [51]:
df2 = df2.rename(columns={"qty":"quantity"})

In [52]:
df2["menu"] = df2["menu"].astype(str).str.strip().str.title()
df2["menu"].value_counts()

menu
Latte        3
Americano    2
Mocha        2
Name: count, dtype: int64

In [53]:
df2["price"] = (
    df2["price"]
    .astype(str)
    .str.replace(",","",regex=False)
    .str.replace("원","",regex=False)
    .str.strip()
)

df2["price"] = pd.to_numeric(df2["price"],errors="coerce")
df2["price"].isnull().sum()

np.int64(1)

In [54]:
df2["price"] = (
    df2["price"]
    .astype(str)
    .str.replace(r"[^0-9]", "", regex=True)  # 숫자(0-9) 제외 전부 제거
)

df2["price"] = pd.to_numeric(df2["price"], errors="coerce")
df2["price"].isnull().sum()

np.int64(1)

In [55]:
# quantity도 숫자로 정리
df2["quantity"] = pd.to_numeric(df2["quantity"], errors="coerce")

# 핵심 변수 결측은 삭제(간단 버전)
clean = df2.dropna(subset=["price","quantity"]).copy()
clean.shape

(4, 7)

In [56]:
clean.duplicated().sum()

np.int64(0)

In [57]:
clean = clean.drop_duplicates(keep="first")
clean.duplicated().sum()

np.int64(0)

In [58]:
clean["sales"] = clean["price"] * clean["quantity"]

meeting_table = clean.loc[cond_paid & cond_storeA & cond_morning, ["date","time","store","menu","price","quantity","sales","paid"]].sort_values(
    by=["date","store","time"],
    ascending=[True, True, True]
)

meeting_table

         date   time store       menu    price  quantity    sales  paid
0  2026-01-01  09:10     A  Americano  45000.0       2.0  90000.0  true
1  2026/01/01  09:12     A      Latte  50000.0       1.0  50000.0  true

In [22]:
meeting_table.to_csv("cafe_sales_clean_v1.csv", index=False, encoding="utf-8-sig")