In [1]:
import pandas as pd
import numpy as np

In [66]:
raw = [
    {"order_id":"O001","date":"2026-01-01 09:12","store":"광교점","menu":"Americano","price":"4,500원","qty":"2","paid":"TRUE","channel":"kiosk"},
    {"order_id":"O002","date":"2026/01/01 10:05","store":"광교점","menu":" Latte ","price":"5000","qty":1,"paid":"True","channel":"app"},
    {"order_id":"O003","date":"2026-01-02 12:20","store":"광교점","menu":"Mocha","price":None,"qty":2,"paid":"FALSE","channel":"kiosk"},
    {"order_id":"O004","date":"2026-01-03 15:40","store":"수원점","menu":"Americano","price":"4500","qty":None,"paid":True,"channel":"app"},
    {"order_id":"O005","date":"2026-01-03 18:10","store":"수원점","menu":"latte","price":"5,000원","qty":"3","paid":"TRUE","channel":"kiosk"},
    {"order_id":"O006","date":"2026-01-04 08:55","store":"수원점","menu":"Vanilla Latte","price":"5800원","qty":"1","paid":"TRUE","channel":"app"},
    {"order_id":"O007","date":"2026-01-04 09:10","store":"광교점","menu":"Mocha","price":"5500","qty":"1","paid":"FALSE","channel":"kiosk"},
    {"order_id":"O008","date":"2026-01-05 11:00","store":"광교점","menu":"Americano","price":"4500원","qty":"1","paid":"TRUE","channel":"app"},
]

df = pd.DataFrame(raw)
df.head()

  order_id              date store       menu   price   qty   paid channel
0     O001  2026-01-01 09:12   광교점  Americano  4,500원     2   TRUE   kiosk
1     O002  2026/01/01 10:05   광교점     Latte     5000     1   True     app
2     O003  2026-01-02 12:20   광교점      Mocha    None     2  FALSE   kiosk
3     O004  2026-01-03 15:40   수원점  Americano    4500  None   True     app
4     O005  2026-01-03 18:10   수원점      latte  5,000원     3   TRUE   kiosk

In [25]:
df.describe()

       order_id              date store       menu   price qty  paid channel
count         8                 8     8          8       7   7     8       8
unique        8                 8     2          5       7   5     4       2
top        O001  2026-01-01 09:12   광교점  Americano  4,500원   1  TRUE   kiosk
freq          1                 1     5          3       1   3     4       4

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  8 non-null      object
 1   date      8 non-null      object
 2   store     8 non-null      object
 3   menu      8 non-null      object
 4   price     7 non-null      object
 5   qty       7 non-null      object
 6   paid      8 non-null      object
 7   channel   8 non-null      object
dtypes: object(8)
memory usage: 640.0+ bytes

In [67]:
df["date"] = pd.to_datetime(df["date"], errors="coerce")
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day_name"] = df["date"].dt.day_name() # 요일(영문)
df["ym"] = df["date"].dt.to_period("M").astype(str) # "2026-01" 형태

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  8 non-null      object
 1   date      7 non-null      datetime64[ns]
 2   store     8 non-null      object
 3   menu      8 non-null      object
 4   price     7 non-null      object
 5   qty       7 non-null      object
 6   paid      8 non-null      object
 7   channel   8 non-null      object
 8   year      7 non-null      float64
 9   month     7 non-null      float64
 10  day_name  7 non-null      object
 11  ym        8 non-null      object
dtypes: datetime64[ns](1), float64(2), object(9)
memory usage: 896.0+ bytes

In [11]:
df.describe()

                                date    year  month
count                              7     7.0    7.0
mean   2026-01-03 15:29:34.285714176  2026.0    1.0
min              2026-01-01 09:12:00  2026.0    1.0
25%              2026-01-03 02:00:00  2026.0    1.0
50%              2026-01-03 18:10:00  2026.0    1.0
75%              2026-01-04 09:02:30  2026.0    1.0
max              2026-01-05 11:00:00  2026.0    1.0
std                              NaN     0.0    0.0

In [12]:
df.head()

,order_id,date,store,menu,price,qty,paid,channel,year,month,day_name,ym
0,O001,2026-01-01 09:12:00,광교점,Americano,"4,500원",2,TRUE,kiosk,2026.0,1.0,Thursday,2026-01
1,O002,NaT,광교점,Latte,5000,1,True,app,NaN,NaN,NaN,NaT
2,O003,2026-01-02 12:20:00,광교점,Mocha,None,2,FALSE,kiosk,2026.0,1.0,Friday,2026-01
3,O004,2026-01-03 15:40:00,수원점,Americano,4500,None,True,app,2026.0,1.0,Saturday,2026-01
4,O005,2026-01-03 18:10:00,수원점,latte,"5,000원",3,TRUE,kiosk,2026.0,1.0,Saturday,2026-01

In [69]:
df["menu"] = df["menu"].astype(str).str.strip().str.title()

In [70]:
df.head()

,order_id,date,store,menu,price,qty,paid,channel,year,month,day_name,ym
0,O001,2026-01-01 09:12:00,광교점,Americano,"4,500원",2,TRUE,kiosk,2026.0,1.0,Thursday,2026-01
1,O002,NaT,광교점,Latte,5000,1,True,app,NaN,NaN,NaN,NaT
2,O003,2026-01-02 12:20:00,광교점,Mocha,None,2,FALSE,kiosk,2026.0,1.0,Friday,2026-01
3,O004,2026-01-03 15:40:00,수원점,Americano,4500,None,True,app,2026.0,1.0,Saturday,2026-01
4,O005,2026-01-03 18:10:00,수원점,Latte,"5,000원",3,TRUE,kiosk,2026.0,1.0,Saturday,2026-01

In [ ]:
df["price"] = (
    df["price"]
    .astype(str)
    .str.replace(",","",regex=False)
    .str.replace("원","",regex=False)
)
df["price"] = pd.to_numeric(df["price"], errors="coerce") # -> float64

In [72]:
df

,order_id,date,store,menu,price,qty,paid,channel,year,month,day_name,ym
0,O001,2026-01-01 09:12:00,광교점,Americano,4500.0,2,TRUE,kiosk,2026.0,1.0,Thursday,2026-01
1,O002,NaT,광교점,Latte,5000.0,1,True,app,NaN,NaN,NaN,NaT
2,O003,2026-01-02 12:20:00,광교점,Mocha,NaN,2,FALSE,kiosk,2026.0,1.0,Friday,2026-01
3,O004,2026-01-03 15:40:00,수원점,Americano,4500.0,None,True,app,2026.0,1.0,Saturday,2026-01
4,O005,2026-01-03 18:10:00,수원점,Latte,5000.0,3,TRUE,kiosk,2026.0,1.0,Saturday,2026-01
5,O006,2026-01-04 08:55:00,수원점,Vanilla Latte,5800.0,1,TRUE,app,2026.0,1.0,Sunday,2026-01
6,O007,2026-01-04 09:10:00,광교점,Mocha,5500.0,1,FALSE,kiosk,2026.0,1.0,Sunday,2026-01
7,O008,2026-01-05 11:00:00,광교점,Americano,4500.0,1,TRUE,app,2026.0,1.0,Monday,2026-01

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  8 non-null      object
 1   date      7 non-null      datetime64[ns]
 2   store     8 non-null      object
 3   menu      8 non-null      object
 4   price     7 non-null      float64
 5   qty       7 non-null      object
 6   paid      8 non-null      object
 7   channel   8 non-null      object
 8   year      7 non-null      float64
 9   month     7 non-null      float64
 10  day_name  7 non-null      object
 11  ym        8 non-null      object
dtypes: datetime64[ns](1), float64(3), object(8)
memory usage: 896.0+ bytes

In [ ]:
df["qty"] = pd.to_numeric(df["qty"], errors="coerce") # -> float

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  8 non-null      object
 1   date      7 non-null      datetime64[ns]
 2   store     8 non-null      object
 3   menu      8 non-null      object
 4   price     7 non-null      float64
 5   qty       7 non-null      float64
 6   paid      8 non-null      object
 7   channel   8 non-null      object
 8   year      7 non-null      float64
 9   month     7 non-null      float64
 10  day_name  7 non-null      object
 11  ym        8 non-null      object
dtypes: datetime64[ns](1), float64(4), object(7)
memory usage: 896.0+ bytes

In [32]:
df.describe()

                                date        price       qty    year  month
count                              7     7.000000  7.000000     7.0    7.0
mean   2026-01-03 15:29:34.285714176  4971.428571  1.571429  2026.0    1.0
min              2026-01-01 09:12:00  4500.000000  1.000000  2026.0    1.0
25%              2026-01-03 02:00:00  4500.000000  1.000000  2026.0    1.0
50%              2026-01-03 18:10:00  5000.000000  1.000000  2026.0    1.0
75%              2026-01-04 09:02:30  5250.000000  2.000000  2026.0    1.0
max              2026-01-05 11:00:00  5800.000000  3.000000  2026.0    1.0
std                              NaN   521.901286  0.786796     0.0    0.0

In [33]:
df

,order_id,date,store,menu,price,qty,paid,channel,year,month,day_name,ym
0,O001,2026-01-01 09:12:00,광교점,Americano,4500.0,2.0,TRUE,kiosk,2026.0,1.0,Thursday,2026-01
1,O002,NaT,광교점,Latte,5000.0,1.0,True,app,NaN,NaN,NaN,NaT
2,O003,2026-01-02 12:20:00,광교점,Mocha,NaN,2.0,FALSE,kiosk,2026.0,1.0,Friday,2026-01
3,O004,2026-01-03 15:40:00,수원점,Americano,4500.0,NaN,True,app,2026.0,1.0,Saturday,2026-01
4,O005,2026-01-03 18:10:00,수원점,Latte,5000.0,3.0,TRUE,kiosk,2026.0,1.0,Saturday,2026-01
5,O006,2026-01-04 08:55:00,수원점,Vanilla Latte,5800.0,1.0,TRUE,app,2026.0,1.0,Sunday,2026-01
6,O007,2026-01-04 09:10:00,광교점,Mocha,5500.0,1.0,FALSE,kiosk,2026.0,1.0,Sunday,2026-01
7,O008,2026-01-05 11:00:00,광교점,Americano,4500.0,1.0,TRUE,app,2026.0,1.0,Monday,2026-01

In [76]:
df["qty"] = df["qty"].fillna(1)   # 실무에서 1로 대체하는 간단 예시(전략 설명)
df["qty"] = df["qty"].astype(int) # -> int

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  8 non-null      object
 1   date      7 non-null      datetime64[ns]
 2   store     8 non-null      object
 3   menu      8 non-null      object
 4   price     7 non-null      float64
 5   qty       8 non-null      int64
 6   paid      8 non-null      object
 7   channel   8 non-null      object
 8   year      7 non-null      float64
 9   month     7 non-null      float64
 10  day_name  7 non-null      object
 11  ym        8 non-null      object
dtypes: datetime64[ns](1), float64(3), int64(1), object(7)
memory usage: 896.0+ bytes

In [ ]:
def to_bool(x):
    if isinstance(x, bool):
        return x
    x = str(x).strip().lower()
    return x in ["true", "1", "yes", "y"] 
    # in 안의 경우는 True 리턴, in에 없는 경우는 False 리턴

df["paid"] = df["paid"].apply(to_bool) # -> bool

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  8 non-null      object
 1   date      7 non-null      datetime64[ns]
 2   store     8 non-null      object
 3   menu      8 non-null      object
 4   price     7 non-null      float64
 5   qty       8 non-null      int64
 6   paid      8 non-null      bool
 7   channel   8 non-null      object
 8   year      7 non-null      float64
 9   month     7 non-null      float64
 10  day_name  7 non-null      object
 11  ym        8 non-null      object
dtypes: bool(1), datetime64[ns](1), float64(3), int64(1), object(6)
memory usage: 840.0+ bytes

In [ ]:
df["sales"] = np.where(df["paid"], df["price"]*df["qty"], 0) # -> float64
df.head()

,order_id,date,store,menu,price,qty,paid,channel,year,month,day_name,ym,sales
0,O001,2026-01-01 09:12:00,광교점,Americano,4500.0,2,True,kiosk,2026.0,1.0,Thursday,2026-01,9000.0
1,O002,NaT,광교점,Latte,5000.0,1,True,app,NaN,NaN,NaN,NaT,5000.0
2,O003,2026-01-02 12:20:00,광교점,Mocha,NaN,2,False,kiosk,2026.0,1.0,Friday,2026-01,0.0
3,O004,2026-01-03 15:40:00,수원점,Americano,4500.0,1,True,app,2026.0,1.0,Saturday,2026-01,4500.0
4,O005,2026-01-03 18:10:00,수원점,Latte,5000.0,3,True,kiosk,2026.0,1.0,Saturday,2026-01,15000.0

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  8 non-null      object
 1   date      7 non-null      datetime64[ns]
 2   store     8 non-null      object
 3   menu      8 non-null      object
 4   price     7 non-null      float64
 5   qty       8 non-null      int64
 6   paid      8 non-null      bool
 7   channel   8 non-null      object
 8   year      7 non-null      float64
 9   month     7 non-null      float64
 10  day_name  7 non-null      object
 11  ym        8 non-null      object
 12  sales     8 non-null      float64
dtypes: bool(1), datetime64[ns](1), float64(4), int64(1), object(6)
memory usage: 904.0+ bytes

In [82]:
store_summary = df.groupby("store").agg( 
    total_sales = ("sales","sum"),
    orders=("order_id","count"),
    paid_rate=("paid","mean")
).reset_index()

store_summary

  store  total_sales  orders  paid_rate
0   광교점      18500.0       5        0.6
1   수원점      25300.0       3        1.0

In [83]:
ym_day = df.groupby(["ym","day_name"]).agg( 
    total_sales=("sales","sum"),
    orders=("order_id","count"),
    paid_rate=("paid","mean")
)
ym_day

                  total_sales  orders  paid_rate
ym      day_name
2026-01 Friday            0.0       1        0.0
        Monday         4500.0       1        1.0
        Saturday      19500.0       2        1.0
        Sunday         5800.0       2        0.5
        Thursday       9000.0       1        1.0

In [84]:
ym_day = ym_day.reset_index() 
ym_day

        ym  day_name  total_sales  orders  paid_rate
0  2026-01    Friday          0.0       1        0.0
1  2026-01    Monday       4500.0       1        1.0
2  2026-01  Saturday      19500.0       2        1.0
3  2026-01    Sunday       5800.0       2        0.5
4  2026-01  Thursday       9000.0       1        1.0

In [85]:
pivot_sales = ym_day.pivot(index="ym",columns="day_name",values="total_sales").fillna(0)
pivot_sales

day_name  Friday  Monday  Saturday  Sunday  Thursday
ym
2026-01      0.0  4500.0   19500.0  5800.0    9000.0

In [86]:
menu_map = pd.DataFrame([
    {"menu":"Americano", "category":"Coffee"},
    {"menu":"Latte", "category":"Coffee"},
    {"menu":"Mocha", "category":"Coffee"},
    {"menu":"Vanilla Latte", "category":"Latte Variations"},
])

menu_map

            menu          category
0      Americano            Coffee
1          Latte            Coffee
2          Mocha            Coffee
3  Vanilla Latte  Latte Variations

In [48]:
df2 = df.merge(menu_map, on="menu", how="left")
df2[["menu","category"]].drop_duplicates()

            menu          category
0      Americano            Coffee
1          Latte            Coffee
2          Mocha            Coffee
5  Vanilla Latte  Latte Variations

In [49]:
df2

,order_id,date,store,menu,price,qty,paid,channel,year,month,day_name,ym,sales,category
0,O001,2026-01-01 09:12:00,광교점,Americano,4500.0,2,True,kiosk,2026.0,1.0,Thursday,2026-01,9000.0,Coffee
1,O002,NaT,광교점,Latte,5000.0,1,True,app,NaN,NaN,NaN,NaT,5000.0,Coffee
2,O003,2026-01-02 12:20:00,광교점,Mocha,NaN,2,False,kiosk,2026.0,1.0,Friday,2026-01,0.0,Coffee
3,O004,2026-01-03 15:40:00,수원점,Americano,4500.0,1,True,app,2026.0,1.0,Saturday,2026-01,4500.0,Coffee
4,O005,2026-01-03 18:10:00,수원점,Latte,5000.0,3,True,kiosk,2026.0,1.0,Saturday,2026-01,15000.0,Coffee
5,O006,2026-01-04 08:55:00,수원점,Vanilla Latte,5800.0,1,True,app,2026.0,1.0,Sunday,2026-01,5800.0,Latte Variations
6,O007,2026-01-04 09:10:00,광교점,Mocha,5500.0,1,False,kiosk,2026.0,1.0,Sunday,2026-01,0.0,Coffee
7,O008,2026-01-05 11:00:00,광교점,Americano,4500.0,1,True,app,2026.0,1.0,Monday,2026-01,4500.0,Coffee

In [87]:
channel_map = {"kiosk":"키오스크", "app":"앱"}
df2["channel_kr"] = df2["channel"].map(channel_map).fillna("기타")
df2[["channel","channel_kr"]].drop_duplicates()

  channel channel_kr
0   kiosk       키오스크
1     app          앱

In [89]:
df2.head()

,order_id,date,store,menu,price,qty,paid,channel,year,month,day_name,ym,sales,category,channel_kr,grade
0,O001,2026-01-01 09:12:00,광교점,Americano,4500.0,2,True,kiosk,2026.0,1.0,Thursday,2026-01,9000.0,Coffee,키오스크,B
1,O002,NaT,광교점,Latte,5000.0,1,True,app,NaN,NaN,NaN,NaT,5000.0,Coffee,앱,B
2,O003,2026-01-02 12:20:00,광교점,Mocha,NaN,2,False,kiosk,2026.0,1.0,Friday,2026-01,0.0,Coffee,키오스크,C
3,O004,2026-01-03 15:40:00,수원점,Americano,4500.0,1,True,app,2026.0,1.0,Saturday,2026-01,4500.0,Coffee,앱,B
4,O005,2026-01-03 18:10:00,수원점,Latte,5000.0,3,True,kiosk,2026.0,1.0,Saturday,2026-01,15000.0,Coffee,키오스크,A

In [90]:
def sales_grade(row):
    if row["sales"] >= 10000:
        return "A" 
    elif row["sales"] > 0:
        return "B" 
    else:
        return "C"
    
df2["grade"] = df2.apply(sales_grade, axis=1)
df2[["order_id","sales","grade"]]

  order_id    sales grade
0     O001   9000.0     B
1     O002   5000.0     B
2     O003      0.0     C
3     O004   4500.0     B
4     O005  15000.0     A
5     O006   5800.0     B
6     O007      0.0     C
7     O008   4500.0     B

In [91]:
summary_A = df.groupby(["ym","day_name"]).agg( 
    total_sales=("sales","sum"), 
    paid_rate=("paid","mean")
).reset_index()  

summary_A

        ym  day_name  total_sales  paid_rate
0  2026-01    Friday          0.0        0.0
1  2026-01    Monday       4500.0        1.0
2  2026-01  Saturday      19500.0        1.0
3  2026-01    Sunday       5800.0        0.5
4  2026-01  Thursday       9000.0        1.0

In [92]:
summary_A_pivot = summary_A.pivot(index="ym", columns="day_name", values="total_sales").fillna(0) 
summary_A_pivot

day_name  Friday  Monday  Saturday  Sunday  Thursday
ym
2026-01      0.0  4500.0   19500.0  5800.0    9000.0

In [93]:
menu_summary = df2.groupby(["category","menu"]).agg( 
    total_sales=("sales","sum"),
    total_qty=("qty","sum"), 
    orders=("order_id","count"),
    paid_rate=("paid","mean")
).reset_index() 

menu_summary

           category           menu  total_sales  total_qty  orders  paid_rate
0            Coffee      Americano      18000.0          4       3        1.0
1            Coffee          Latte      20000.0          4       2        1.0
2            Coffee          Mocha          0.0          3       2        0.0
3  Latte Variations  Vanilla Latte       5800.0          1       1        1.0

In [94]:
menu_summary = menu_summary.sort_values("total_sales", ascending=False)
menu_summary

           category           menu  total_sales  total_qty  orders  paid_rate
1            Coffee          Latte      20000.0          4       2        1.0
0            Coffee      Americano      18000.0          4       3        1.0
3  Latte Variations  Vanilla Latte       5800.0          1       1        1.0
2            Coffee          Mocha          0.0          3       2        0.0

In [95]:
menu_summary = menu_summary.sort_values(by=["category", "menu", "total_sales"], 
                                        ascending=[True, True, True]).reset_index(drop=True)
menu_summary

           category           menu  total_sales  total_qty  orders  paid_rate
0            Coffee      Americano      18000.0          4       3        1.0
1            Coffee          Latte      20000.0          4       2        1.0
2            Coffee          Mocha          0.0          3       2        0.0
3  Latte Variations  Vanilla Latte       5800.0          1       1        1.0

In [96]:
import os 
os.makedirs("data", exist_ok=True)

summary_A.to_csv("data/summary_A_long.csv", index=False)
summary_A_pivot.to_csv("data/summary_A_pivot.csv")
menu_summary.to_csv("data/summary_B_menu.csv", index=False)

In [97]:
check = pd.read_csv("data/summary_B_menu.csv")
check.head()

           category           menu  total_sales  total_qty  orders  paid_rate
0            Coffee      Americano      18000.0          4       3        1.0
1            Coffee          Latte      20000.0          4       2        1.0
2            Coffee          Mocha          0.0          3       2        0.0
3  Latte Variations  Vanilla Latte       5800.0          1       1        1.0

In [98]:
import pandas as pd

# 원본 로그(주문 1건 = 1행)
df = pd.DataFrame([
    {"date": "2026-01-01", "store": "광교점", "menu": "Americano", "sales": 9000},
    {"date": "2026-01-01", "store": "광교점", "menu": "Latte",     "sales": 5000},
    {"date": "2026-01-02", "store": "광교점", "menu": "Latte",     "sales": 5000},
    {"date": "2026-01-03", "store": "수원점", "menu": "Americano", "sales": 4500},
    {"date": "2026-01-03", "store": "수원점", "menu": "Mocha",     "sales": 5500},
])

# 날짜 -> datetime, 월(ym) 컬럼 생성
df["date"] = pd.to_datetime(df["date"])
df["ym"] = df["date"].dt.to_period("M").astype(str)

print(" 원본 로그(주문 1건 단위):")
print(df)

 원본 로그(주문 1건 단위):
        date store       menu  sales       ym
0 2026-01-01   광교점  Americano   9000  2026-01
1 2026-01-01   광교점      Latte   5000  2026-01
2 2026-01-02   광교점      Latte   5000  2026-01
3 2026-01-03   수원점  Americano   4500  2026-01
4 2026-01-03   수원점      Mocha   5500  2026-01

In [99]:
# 1) 주문 단위 -> 메뉴 단위 (메뉴별 매출 합계)
menu_report = df.groupby("menu")["sales"].sum().reset_index(name="total_sales")
print("\n GroupBy 결과(메뉴 단위) = 메뉴별 매출 합계:")
print(menu_report)

 GroupBy 결과(메뉴 단위) = 메뉴별 매출 합계:
        menu  total_sales
0  Americano        13500
1      Latte        10000
2      Mocha         5500

In [100]:
# 2) 주문 단위 -> 매장 단위 (매장별 매출 합계)
store_report = df.groupby("store")["sales"].sum().reset_index(name="total_sales")
print("\n GroupBy 결과(매장 단위) = 매장별 매출 합계:")
print(store_report)

 GroupBy 결과(매장 단위) = 매장별 매출 합계:
  store  total_sales
0   광교점        19000
1   수원점        10000

In [101]:
# 3) 주문 단위 -> 월 단위 (월별 매출 합계)
month_report = df.groupby("ym")["sales"].sum().reset_index(name="total_sales")
print("\n GroupBy 결과(월 단위) = 월별 매출 합계:")
print(month_report)

 GroupBy 결과(월 단위) = 월별 매출 합계:
        ym  total_sales
0  2026-01        29000

In [102]:
# (추가) 순위/비교가 쉬워짐: 메뉴 매출 TOP 정렬
top_menu = menu_report.sort_values("total_sales", ascending=False)
print("\n 메뉴 매출 TOP(정렬로 순위 확인):")
print(top_menu)

 메뉴 매출 TOP(정렬로 순위 확인):
        menu  total_sales
0  Americano        13500
1      Latte        10000
2      Mocha         5500

In [106]:
import pandas as pd

# 1) 주문(원본 로그) 데이터: "주문 1건 = 행 1개"
df = pd.DataFrame([
    {"date": "2026-01-01", "store": "광교점", "menu": "Americano", "sales": 9000, "paid": True},
    {"date": "2026-01-01", "store": "광교점", "menu": "Latte",     "sales": 5000, "paid": True},
    {"date": "2026-01-02", "store": "광교점", "menu": "Latte",     "sales": 0,    "paid": False},
    {"date": "2026-01-03", "store": "수원점", "menu": "Americano", "sales": 4500, "paid": True},
    {"date": "2026-01-03", "store": "수원점", "menu": "Mocha",     "sales": 0,    "paid": False},
])

# 날짜를 datetime으로 바꾸고, 월(ym) 컬럼 생성 (월별 그룹화용)
df["date"] = pd.to_datetime(df["date"])
df["ym"] = df["date"].dt.to_period("M").astype(str)

print("원본 로그")
print(df)

원본 로그
        date store       menu  sales   paid       ym
0 2026-01-01   광교점  Americano   9000   True  2026-01
1 2026-01-01   광교점      Latte   5000   True  2026-01
2 2026-01-02   광교점      Latte      0  False  2026-01
3 2026-01-03   수원점  Americano   4500   True  2026-01
4 2026-01-03   수원점      Mocha      0  False  2026-01

In [107]:
# 2) 메뉴별 매출 합계: "Americano가 총 얼마 벌었나?"
menu_sales = df.groupby("menu")["sales"].sum().reset_index()
print("\n메뉴별 매출 합계")
print(menu_sales)

# 3) 매장별 주문 수: "광교점은 주문이 몇 건인가?"
store_orders = df.groupby("store")["menu"].count().reset_index(name="orders")
print("\n매장별 주문 수")
print(store_orders)

# 4) 월별 결제 성공률: "이번 달 결제 실패가 늘었나?"
# paid가 True/False이면 mean()이 성공률(비율)처럼 동작합니다.
monthly_paid_rate = df.groupby("ym")["paid"].mean().reset_index(name="paid_rate")
print("\n월별 결제 성공률")
print(monthly_paid_rate)

메뉴별 매출 합계
        menu  sales
0  Americano  13500
1      Latte   5000
2      Mocha      0

매장별 주문 수
  store  orders
0   광교점       3
1   수원점       2

월별 결제 성공률
        ym  paid_rate
0  2026-01        0.6

In [2]:
import pandas as pd

# 예시 데이터(주문 1건 = 1행)
df = pd.DataFrame([
    {"date": "2026-01-01", "menu": "Americano", "sales": 9000},
    {"date": "2026-01-02", "menu": "Latte",     "sales": 5000},
    {"date": "2026-01-03", "menu": "Latte",     "sales": 5000},
    {"date": "2026-01-06", "menu": "Americano", "sales": 4500},
    {"date": "2026-01-07", "menu": "Mocha",     "sales": 5500},
])

# 날짜 처리 + 파생 컬럼(월/요일) 만들기
df["date"] = pd.to_datetime(df["date"])
df["ym"] = df["date"].dt.to_period("M").astype(str)     # "2026-01"
df["day_name"] = df["date"].dt.day_name()               # Monday, Tuesday...

print("원본 로그")
print(df)

# 1) 단일 기준 그룹화: menu 하나만
menu_report = (
    df.groupby("menu")["sales"].sum()
      .reset_index(name="total_sales")
      .sort_values("total_sales", ascending=False)
)

print("\n 단일 기준(menu) 그룹화: 메뉴별 매출 TOP")
print(menu_report)

# 2) 다중 기준 그룹화: ym(월) + day_name(요일)
ym_day_report = (
    df.groupby(["ym", "day_name"])["sales"].sum()
      .reset_index(name="total_sales")
      .sort_values(["ym", "total_sales"], ascending=[True, False])
)

print("\n 다중 기준(ym + day_name) 그룹화: 월별-요일별 매출")
print(ym_day_report)

원본 로그
        date       menu  sales       ym   day_name
0 2026-01-01  Americano   9000  2026-01   Thursday
1 2026-01-02      Latte   5000  2026-01     Friday
2 2026-01-03      Latte   5000  2026-01   Saturday
3 2026-01-06  Americano   4500  2026-01    Tuesday
4 2026-01-07      Mocha   5500  2026-01  Wednesday

 단일 기준(menu) 그룹화: 메뉴별 매출 TOP
        menu  total_sales
0  Americano        13500
1      Latte        10000
2      Mocha         5500

 다중 기준(ym + day_name) 그룹화: 월별-요일별 매출
        ym   day_name  total_sales
2  2026-01   Thursday         9000
4  2026-01  Wednesday         5500
0  2026-01     Friday         5000
1  2026-01   Saturday         5000
3  2026-01    Tuesday         4500

In [3]:
# 1) 단일 기준 그룹화: menu 하나만
menu_report = (
    df.groupby("menu")["sales"].sum()
      .reset_index(name="total_sales")
      .sort_values("total_sales", ascending=False)
)

print("\n 단일 기준(menu) 그룹화: 메뉴별 매출 TOP")
print(menu_report)

 단일 기준(menu) 그룹화: 메뉴별 매출 TOP
        menu  total_sales
0  Americano        13500
1      Latte        10000
2      Mocha         5500

In [4]:
# 2) 다중 기준 그룹화: ym(월) + day_name(요일)
ym_day_report = (
    df.groupby(["ym", "day_name"])["sales"].sum()
      .reset_index(name="total_sales")
      .sort_values(["ym", "total_sales"], ascending=[True, False])
)

print("\n 다중 기준(ym + day_name) 그룹화: 월별-요일별 매출")
print(ym_day_report)

 다중 기준(ym + day_name) 그룹화: 월별-요일별 매출
        ym   day_name  total_sales
2  2026-01   Thursday         9000
4  2026-01  Wednesday         5500
0  2026-01     Friday         5000
1  2026-01   Saturday         5000
3  2026-01    Tuesday         4500

In [6]:
import pandas as pd

# 예시 데이터(주문 1건 = 1행)
df = pd.DataFrame([
    {"store": "광교점", "menu": "Americano", "sales": 9000, "paid": True},
    {"store": "광교점", "menu": "Latte",     "sales": 5000, "paid": True},
    {"store": "광교점", "menu": "Latte",     "sales": 0,    "paid": False},
    {"store": "수원점", "menu": "Americano", "sales": 4500, "paid": True},
    {"store": "수원점", "menu": "Mocha",     "sales": 0,    "paid": False},
])

print("원본 로그")
print(df)

# 실무 리포트용: agg()로 여러 지표를 한 번에 만들기 (매장별 요약표)
report = df.groupby("store").agg(
    total_sales=("sales", "sum"),   # 매출 합계
    orders=("menu", "count"),       # 주문 수(행 개수)
    paid_rate=("paid", "mean"),     # 결제 성공률(True/False 평균)
).reset_index()

print("\n 매장별 리포트 요약표(agg로 한 번에 생성)")
print(report)

원본 로그
  store       menu  sales   paid
0   광교점  Americano   9000   True
1   광교점      Latte   5000   True
2   광교점      Latte      0  False
3   수원점  Americano   4500   True
4   수원점      Mocha      0  False

 매장별 리포트 요약표(agg로 한 번에 생성)
  store  total_sales  orders  paid_rate
0   광교점        14000       3   0.666667
1   수원점         4500       2   0.500000

In [7]:
# 실무 리포트용: agg()로 여러 지표를 한 번에 만들기 (매장별 요약표)
report = df.groupby("store").agg(
    total_sales=("sales", "sum"),   # 매출 합계
    orders=("menu", "count"),       # 주문 수(행 개수)
    paid_rate=("paid", "mean"),     # 결제 성공률(True/False 평균)
).reset_index()

print("\n 매장별 리포트 요약표(agg로 한 번에 생성)")
print(report)

 매장별 리포트 요약표(agg로 한 번에 생성)
  store  total_sales  orders  paid_rate
0   광교점        14000       3   0.666667
1   수원점         4500       2   0.500000

In [8]:
import pandas as pd

# 예시 데이터(일부 조합이 반복되도록 일부러 2행 넣음: 2026-01 + Mon)
df = pd.DataFrame([
    {"ym": "2026-01", "day": "Mon", "sales": 100},
    {"ym": "2026-01", "day": "Mon", "sales": 50},   # 같은 조합이 2개라서 pivot이 바로 안 됨
    {"ym": "2026-01", "day": "Tue", "sales": 80},
    {"ym": "2026-02", "day": "Mon", "sales": 120},
    # 2026-02의 Tue가 없어서 피벗 후 NaN이 생길 수 있음
])

print("원본(long 형태)")
print(df)

원본(long 형태)
        ym  day  sales
0  2026-01  Mon    100
1  2026-01  Mon     50
2  2026-01  Tue     80
3  2026-02  Mon    120

In [9]:
# 실수 포인트 1) 같은 ym+day 조합이 여러 행이면 pivot이 바로 안 됨
# 해결: GroupBy로 먼저 1개 값(합계/평균 등)으로 요약
summary = df.groupby(["ym", "day"])["sales"].sum().reset_index(name="total_sales")

print("\nGroupBy로 먼저 요약(중복 조합 해결)")
print(summary)

GroupBy로 먼저 요약(중복 조합 해결)
        ym  day  total_sales
0  2026-01  Mon          150
1  2026-01  Tue           80
2  2026-02  Mon          120

In [10]:
# 1) pivot 방식: 행/열/값을 지정해서 표 만들기
pivot_table = summary.pivot(index="ym", columns="day", values="total_sales")
print("\npivot 결과")
print(pivot_table)

pivot 결과
day        Mon   Tue
ym
2026-01  150.0  80.0
2026-02  120.0   NaN

In [12]:
# 2) unstack 방식: GroupBy 결과(MultiIndex)를 열로 펼치기
multi = df.groupby(["ym", "day"])["sales"].sum()  # MultiIndex Series
print(multi)
unstack_table = multi.unstack()
print("\nunstack 결과")
print(unstack_table)

ym       day
2026-01  Mon    150
         Tue     80
2026-02  Mon    120
Name: sales, dtype: int64

unstack 결과
day        Mon   Tue
ym
2026-01  150.0  80.0
2026-02  120.0   NaN

In [13]:
# 실수 포인트 2) 어떤 조합이 없으면 NaN이 생김
# 리포트에서는 보통 0으로 채움
pivot_filled = pivot_table.fillna(0)
print("\nNaN을 0으로 채운 리포트 표")
print(pivot_filled)

NaN을 0으로 채운 리포트 표
day        Mon   Tue
ym
2026-01  150.0  80.0
2026-02  120.0   0.0

In [15]:
import pandas as pd

df = pd.DataFrame([
    {"menu": " Latte ",        "price": "4,500원", "note": "NEW member"},
    {"menu": "latte",          "price": "5000",     "note": "vip MEMBER"},
    {"menu": "LATTE",          "price": "5,000원",  "note": "Member coupon"},
    {"menu": "Americano",      "price": "4500원",   "note": "guest"},
    {"menu": "Vanilla Latte",  "price": "5,800원",  "note": "new_member"},
])

print("원본")
print(df)

원본
            menu   price           note
0         Latte   4,500원     NEW member
1          latte    5000     vip MEMBER
2          LATTE  5,000원  Member coupon
3      Americano   4500원          guest
4  Vanilla Latte  5,800원     new_member

In [16]:
df["menu_clean"] = df["menu"].str.strip()
print("\nstrip 적용")
print(df[["menu", "menu_clean"]])

strip 적용
            menu     menu_clean
0         Latte           Latte
1          latte          latte
2          LATTE          LATTE
3      Americano      Americano
4  Vanilla Latte  Vanilla Latte

In [18]:
df["menu_lower"] = df["menu_clean"].str.lower()
df["menu_title"] = df["menu_clean"].str.title()

print("\nlower/title 적용")
print(df[["menu_clean", "menu_lower", "menu_title"]])

lower/title 적용
      menu_clean     menu_lower     menu_title
0          Latte          latte          Latte
1          latte          latte          Latte
2          LATTE          latte          Latte
3      Americano      americano      Americano
4  Vanilla Latte  vanilla latte  Vanilla Latte

In [19]:
# note 컬럼에서 'member'가 포함된 행만 필터(대소문자 무시)
member_df = df[df["note"].str.contains("member", case=False, na=False)]
print("\ncontains로 member 관련만 필터")
print(member_df[["note"]])

contains로 member 관련만 필터
            note
0     NEW member
1     vip MEMBER
2  Member coupon
4     new_member

In [20]:
df["price_num"] = (
    df["price"]
      .str.replace(",", "", regex=False)
      .str.replace("원", "", regex=False)
)

df["price_num"] = pd.to_numeric(df["price_num"], errors="coerce")

print("\nreplace + 숫자 변환")
print(df[["price", "price_num"]])

replace + 숫자 변환
    price  price_num
0  4,500원       4500
1    5000       5000
2  5,000원       5000
3   4500원       4500
4  5,800원       5800

In [21]:
import pandas as pd

df = pd.DataFrame({
    "date_str": ["2026/01/02", "2026/01/10", "2026/01/03"],
    "sales": [100, 200, 150]
})

print(df.sort_values("date_str"))  # 문자열 기준 정렬

df["date"] = pd.to_datetime(df["date_str"])
print(df.sort_values("date"))      # datetime 기준 정렬

     date_str  sales
0  2026/01/02    100
2  2026/01/03    150
1  2026/01/10    200
     date_str  sales       date
0  2026/01/02    100 2026-01-02
2  2026/01/03    150 2026-01-03
1  2026/01/10    200 2026-01-10

In [22]:
import pandas as pd

df = pd.DataFrame({
    "date": ["2026-01-01", "2026-01-03", "2026-02-01"],
    "sales": [10000, 15000, 20000]
})

df["date"] = pd.to_datetime(df["date"])  # 핵심 1) datetime 변환

df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day_name"] = df["date"].dt.day_name()

# 연-월(리포트에서 자주 쓰는 키): to_period('M') 활용
df["ym"] = df["date"].dt.to_period("M").astype(str)

print(df)

        date  sales  year  month  day_name       ym
0 2026-01-01  10000  2026      1  Thursday  2026-01
1 2026-01-03  15000  2026      1  Saturday  2026-01
2 2026-02-01  20000  2026      2    Sunday  2026-02

In [23]:
import pandas as pd

orders = pd.DataFrame([
    {"order_id": 1, "date": "2026-01-01", "menu": "Latte",     "sales": 5000, "customer_id": "C01"},
    {"order_id": 2, "date": "2026-01-01", "menu": "Americano", "sales": 4500, "customer_id": "C02"},
    {"order_id": 3, "date": "2026-01-02", "menu": "Cake",      "sales": 6000, "customer_id": "C03"},
])

menu_map = pd.DataFrame([
    {"menu": "Latte",     "category": "Coffee"},
    {"menu": "Americano", "category": "Coffee"},
    # Cake가 빠져있다고 가정(매핑 누락 사례)
])

customers = pd.DataFrame([
    {"customer_id": "C01", "city": "Suwon", "grade": "VIP"},
    {"customer_id": "C02", "city": "Yongin","grade": "NEW"},
    {"customer_id": "C03", "city": "Suwon", "grade": "NORMAL"},
])

print(orders)
print(menu_map)
print(customers)

   order_id        date       menu  sales customer_id
0         1  2026-01-01      Latte   5000         C01
1         2  2026-01-01  Americano   4500         C02
2         3  2026-01-02       Cake   6000         C03
        menu category
0      Latte   Coffee
1  Americano   Coffee
  customer_id    city   grade
0         C01   Suwon     VIP
1         C02  Yongin     NEW
2         C03   Suwon  NORMAL

In [24]:
merged = orders.merge(menu_map, on="menu", how="left")  # 매핑표는 보통 left로 붙임
print(merged)

   order_id        date       menu  sales customer_id category
0         1  2026-01-01      Latte   5000         C01   Coffee
1         2  2026-01-01  Americano   4500         C02   Coffee
2         3  2026-01-02       Cake   6000         C03      NaN

In [25]:
cat_sales = merged.groupby("category")["sales"].sum()
print(cat_sales)

category
Coffee    9500
Name: sales, dtype: int64

In [26]:
check = orders.merge(menu_map, on="menu", how="left", indicator=True)
missing = check[check["_merge"] == "left_only"]  # 왼쪽에만 있음 = 매핑표에 없음
print(missing[["menu", "order_id"]])

   menu  order_id
2  Cake         3

In [27]:
jan = pd.DataFrame([
    {"order_id": 1, "ym": "2026-01", "sales": 5000},
    {"order_id": 2, "ym": "2026-01", "sales": 4500},
])

feb = pd.DataFrame([
    {"order_id": 3, "ym": "2026-02", "sales": 6000},
])

all_orders = pd.concat([jan, feb], ignore_index=True)  # 위아래로 쌓기
print(all_orders)

   order_id       ym  sales
0         1  2026-01   5000
1         2  2026-01   4500
2         3  2026-02   6000

In [28]:
import pandas as pd

df = pd.DataFrame({
    "channel": ["kiosk", "app", "kiosk", "web"]
})

channel_map = {
    "kiosk": "키오스크",
    "app": "앱",
    "web": "웹"
}

df["channel_name"] = df["channel"].map(channel_map)
print(df)

  channel channel_name
0   kiosk         키오스크
1     app            앱
2   kiosk         키오스크
3     web            웹

In [29]:
missing = df[df["channel_name"].isna()]
print(missing)

Empty DataFrame
Columns: [channel, channel_name]
Index: []

In [30]:
import pandas as pd

df = pd.DataFrame({"sales": [0, 3000, 12000]})

def grade_sales(x):
    if x == 0:
        return "C"
    elif x < 10000:
        return "B"
    else:
        return "A"

df["grade"] = df["sales"].apply(grade_sales)
print(df)

   sales grade
0      0     C
1   3000     B
2  12000     A

In [31]:
import pandas as pd

df = pd.DataFrame({"sales": [0, 3000, 12000]})

df["grade_vec"] = "B"
df.loc[df["sales"] == 0, "grade_vec"] = "C"
df.loc[df["sales"] >= 10000, "grade_vec"] = "A"

print(df)

   sales grade_vec
0      0         C
1   3000         B
2  12000         A