In [1]:
import pandas as pd
seoul_2019 = pd.read_csv("./2019.csv",encoding='cp949',parse_dates=["계약일"])

/var/folders/s9/dc7mvn1n1nl45gw342h0m_kr0000gn/T/ipykernel_15266/3729532927.py:2: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  seoul_2019 = pd.read_csv("./2019.csv",encoding='cp949',parse_dates=["계약일"])

In [2]:
seoul_2019.isna().sum()

접수연도                     0
자치구코드                    0
자치구명                     0
법정동코드                    0
법정동명                     0
지번구분                  9661
지번구분명                 9661
본번                    9661
부번                    9661
건물명                   9653
계약일                      0
물건금액(만원)                 0
건물면적(㎡)                  0
토지면적(㎡)              60359
층                     9653
권리구분                128626
취소일                 130673
건축년도                   198
건물용도                     0
신고구분                130673
신고한 개업공인중개사 시군구명    130673
dtype: int64

In [9]:
seoul_2018["지번구분명"].value_counts()

NameError: name 'seoul_2018' is not defined

In [8]:
seoul_2019["지번구분명"].isna().sum()

np.int64(9661)

In [5]:
seoul_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130673 entries, 0 to 130672
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   접수연도              130673 non-null  int64
 1   자치구코드             130673 non-null  int64
 2   자치구명              130673 non-null  object
 3   법정동코드             130673 non-null  int64
 4   법정동명              130673 non-null  object
 5   지번구분              121012 non-null  float64
 6   지번구분명             121012 non-null  object
 7   본번                121012 non-null  object
 8   부번                121012 non-null  float64
 9   건물명               121020 non-null  object
 10  계약일               130673 non-null  datetime64[ns]
 11  물건금액(만원)          130673 non-null  int64
 12  건물면적(㎡)           130673 non-null  float64
 13  토지면적(㎡)           70314 non-null   float64
 14  층                 121020 non-null  float64
 15  권리구분              2047 non-null    object
 16  취소일               0 non-null       float64
 17  건축년도              130475 non-null  float64
 18  건물용도              130673 non-null  object
 19  신고구분              0 non-null       float64
 20  신고한 개업공인중개사 시군구명  0 non-null       float64
dtypes: datetime64[ns](1), float64(9), int64(4), object(7)
memory usage: 20.9+ MB

In [3]:
gangnam = ["역삼동","개포동","청담동","삼성동","대치동","신사동","논현동","압구정동","세곡동","자곡동","율현동","일원동","수서동","도곡동"]
not_gangnam_2019 = seoul_2019[(seoul_2019["자치구명"]=="강남구") & (~seoul_2019["법정동명"].isin(gangnam))]

not_gangnam_2019

Empty DataFrame
Columns: [접수연도, 자치구코드, 자치구명, 법정동코드, 법정동명, 지번구분, 지번구분명, 본번, 부번, 건물명, 계약일, 물건금액(만원), 건물면적(㎡), 토지면적(㎡), 층, 권리구분, 취소일, 건축년도, 건물용도, 신고구분, 신고한 개업공인중개사 시군구명]
Index: []

[0 rows x 21 columns]

In [4]:
yongsan = ["후암동","용산동2가","용산동4가","갈월동","남영동","용산동1가","동자동","서계동","청파동1가","청파동2가","청파동3가","원효로1가","원효로2가","신창동","산천동","청암동","원효로3가","원효로4가","효창동","도원동","용문동","문배동","신계동","한강로1가","한강로2가","용산동3가","용산동5가","한강로3가","이촌동","이태원동","한남동","동빙고동","서빙고동","주성동","용산동6가","보광동"]
not_yongsan_2019 = seoul_2019[(seoul_2019["자치구명"]=="용산구") & (~seoul_2019["법정동명"].isin(yongsan))]

not_yongsan_2019

Empty DataFrame
Columns: [접수연도, 자치구코드, 자치구명, 법정동코드, 법정동명, 지번구분, 지번구분명, 본번, 부번, 건물명, 계약일, 물건금액(만원), 건물면적(㎡), 토지면적(㎡), 층, 권리구분, 취소일, 건축년도, 건물용도, 신고구분, 신고한 개업공인중개사 시군구명]
Index: []

[0 rows x 21 columns]